export const RECOMMENDED_PROJECT_VECTOR = [
  "age",
  "num_platforms",
  "num_telemetry_platforms",
  "self_reported_weekly_play",
  "gdt_total",
  "promis_total",
  "wemwbs_total",
  "bangs_total",
  "telem_nocturnal_sessions",
  "steam_playtime_2weeks_max",
  "steam_playtime_forever_max",
  "steam_unique_games",
  "steam_owned_games_count",
  "daily_played_days",
  "daily_stress_days",
  "cog_mean_accuracy",
  "cog_mean_rt",
  "timeuse_gaming_entries",
  "timeuse_num_days",
];

export const VALIDATION_PROFILE_VARIABLES = [
  "num_platforms",
  "num_telemetry_platforms",
  "telem_nocturnal_sessions",
  "telem_total_sessions",
  "steam_playtime_2weeks_max",
  "steam_playtime_forever_max",
  "timeuse_gaming_entries",
  "timeuse_num_days",
  "promis_total",
  "wemwbs_total",
  "gdt_total",
  "bangs_total",
  "cog_mean_rt",
  "cog_mean_accuracy",
];
